// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250324051118_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DTO.HocSinh", b =>
                {
                    b.Property<string>("MaHS")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.HasKey("MaHS");

                    b.ToTable("HOCSINH");

                    b.HasData(
                        new
                        {
                            MaHS = "HS0001",
                            DiaChi = "Ở đây",
                            Email = "thuandq@uit.edu.vn",
                            GioiTinh = "Nam",
                            HoTen = "Dương Quốc Thuận",
                            NgaySinh = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaHS = "HS0002",
                            DiaChi = "Ở đây",
                            Email = "1234@lmao.com",
                            GioiTinh = "Nam",
                            HoTen = "Tiền Minh Dương",
                            NgaySinh = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DTO.ThamSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuoiToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuoiToiThieu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("THAMSO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SiSoToiDa = 40,
                            TuoiToiDa = 20,
                            TuoiToiThieu = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
